<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em>*</em><?php echo $this->__('Check No#') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Check No#') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_no" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" />
        </span>
    </li>
    <li>
        <div class="field">
            <label for="<?php echo $_code ?>_check_date" class="required"><em>*</em><?php echo $this->__('Check Date:') ?></label>
            <span class="input-box">
                <input id="_check_date" type="text" title="<?php echo $this->__('Check Date:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_date" name="payment[check_date]" value="<?php echo $this->htmlEscape($this->getInfoData('check_date')) ?>" />
                 <em>*</em>
                 <img title="Select date" id="_check_trig" src="<?php echo $this->getSkinUrl('images/calendar.gif');?>" class="v-middle">
            </span>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_payee_name" class="required"><em>*</em><?php echo $this->__('Payee Name:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Payee Name:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_payee_name" name="payment[payee_name]" value="<?php echo $this->htmlEscape($this->getInfoData('payee_name')) ?>" />
        </span>
    </li>
</ul>
<div>
	<?php echo $this->getMethod()->getConfigData('message');?>
</div>

<script type=”text/javascript”>
  //<![CDATA[
  Calendar.setup({
    inputField : '_check_date',
    ifFormat : '%e/%m/%y',
    button : '_check_trig',
    align : 'Bl',
    singleClick : true
  });
//]]>
</script>